### ISSUE TITLE
Relax lower bounds on (test) dependencies

### ISSUE THREAD

**Issue by sternenseemann** [phadej/puresat#6]
puresat has the following bounds:

```
QuickCheck >=2.15.0.1 && <2.16,
primitive >=0.9.0.0 && <0.10,
tasty >=1.5 && <1.6,
tasty-quickcheck >=0.11 && <0.12
```

These conflict with the following versions from the current Stackage LTS which work fine from my testing:

* QuickCheck == 2.14.3
* primitive == 0.8.0.0
* tasty == 1.4.3
* tasty-quickcheck == 0.10.2

**Comment by phadej** [comment]
ditto as with `spdx`. I don't test those versions. Don't use Stackage LTS as your base set if you need fresh releases.
